name: Update KB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/run-update-kb.yaml"

jobs:
  gh-pages:
    name: Scrap and Deploy KB
    uses: zaggash/gh-workflows/.github/workflows/action_rancherkb-fuzz-gh-pages.yaml@main
    secrets:
      app_id: ${{ secrets.ZAGGBOT_APP_ID }}
      app_private_key: ${{ secrets.ZAGGBOT_APP_PRIVATE_KEY }}
  
